#!/bin/bash
#shellcheck disable=SC1091
set -euo pipefail

. scripts/env

BODY=$(curl -fsSL "$GRADLE_MINIMUM_URL")
VERSION=$(awk '/JDK</ {getline; gsub(/[^0-9]/, ""); print}' <<<"$BODY")  
if [[ -z "$VERSION" ]]; then
	{
		echo "::error:: Failed to extract Java version."
		echo "Body: $BODY"
	} >&2
	exit
fi
echo "$VERSION"
